[package]
name = "simple"
version = "0.1.1-for-0.0.4-alpha"
authors = ["Eric Harris-Braun <eric@harris-braun.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
hdk = { git = "https://github.com/holochain/holochain-rust" , branch = "release-0.0.4" }
holochain_wasm_utils = { git = "https://github.com/holochain/holochain-rust" , branch = "release-0.0.4" }
holochain_core_types_derive = { git = "https://github.com/holochain/holochain-rust" , branch = "release-0.0.4" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
